/**
 * Material Design 3-ish Color System (Refined)
 * Friendlier contrast, softer neutrals, more complete roles for real UI usage.
 */

import { Platform } from "react-native";

export const Colors = {
  light: {
    primary: "#6444D5",
    onPrimary: "#FFFFFF",
    primaryContainer: "#EADFFB",
    onPrimaryContainer: "#090909",
    secondary: "#645C74",
    onSecondary: "#FFFFFF",
    secondaryContainer: "#F1ECF3",
    onSecondaryContainer: "#4E4258",
    tertiary: "#C469CC",
    onTertiary: "#090909",
    tertiaryContainer: "#F6EFF4",
    onTertiaryContainer: "#4E4258",
    background: "#FDF6FB",
    onBackground: "#1B1B1B",
    surface: "#F6EFF4",
    onSurface: "#090909",
    surfaceVariant: "#F1ECF3",
    onSurfaceVariant: "#4E4258",
    surfaceTint: "#6444D5",
    inverseSurface: "#1F1820",
    inverseOnSurface: "#F2ECF3",
    card: "#F6EFF4",
    cardMuted: "#F1ECF3",
    divider: "#CBC4D2",
    scrim: "rgba(0,0,0,0.32)",
    placeholder: "#7B7481",
    outline: "#CBC4D2",
    outlineVariant: "#7B7481",
    text: "#1B1B1B",
    textSecondary: "#4E4258",
    textTertiary: "#7B7481",
    error: "#DF0C07",
    onError: "#FFFFFF",
    errorContainer: "#FFDAD6",
    onErrorContainer: "#410002",
    success: "#39C07F",
    onSuccess: "#FFFFFF",
    successContainer: "#D9F7E8",
    onSuccessContainer: "#0B3D27",
    warning: "#A5D363",
    onWarning: "#203009",
    warningContainer: "#EEF8DE",
    onWarningContainer: "#31450D",
    info: "#5197FF",
    onInfo: "#FFFFFF",
    infoContainer: "#DBE9FF",
    onInfoContainer: "#153A78",
    tint: "#6444D5",
    tabIconDefault: "#7B7481",
    tabIconSelected: "#6444D5",
    icon: "#4E4258",
    shadow: "#000000",
    elevation1: "#F6EFF4",
    elevation2: "#F1ECF3",
    elevation3: "#EADFFB",
  },
  dark: {
    primary: "#6D65FE",
    onPrimary: "#FCF6FD",
    primaryContainer: "#3F3355",
    onPrimaryContainer: "#F2ECF3",
    secondary: "#565265",
    onSecondary: "#F2ECF3",
    secondaryContainer: "#302C31",
    onSecondaryContainer: "#F2ECF3",
    tertiary: "#B464E8",
    onTertiary: "#F2ECF3",
    tertiaryContainer: "#3F3355",
    onTertiaryContainer: "#F2ECF3",
    background: "#0D0A0E",
    onBackground: "#F2ECF3",
    surface: "#1F1820",
    onSurface: "#F2ECF3",
    surfaceVariant: "#1D191E",
    onSurfaceVariant: "#A19CA2",
    surfaceTint: "#6D65FE",
    inverseSurface: "#F2ECF3",
    inverseOnSurface: "#1F1820",
    card: "#1F1820",
    cardMuted: "#181519",
    divider: "#4E4258",
    scrim: "rgba(0,0,0,0.55)",
    placeholder: "#A19CA2",
    outline: "#4E4258",
    outlineVariant: "#3D393E",
    text: "#F2ECF3",
    textSecondary: "#A19CA2",
    textTertiary: "#8D8891",
    error: "#E76A68",
    onError: "#F2ECF3",
    errorContainer: "#8D1C18",
    onErrorContainer: "#FFDAD6",
    success: "#25984D",
    onSuccess: "#F2ECF3",
    successContainer: "#1A5A32",
    onSuccessContainer: "#D9F7E8",
    warning: "#559400",
    onWarning: "#EAF5DB",
    warningContainer: "#2D4E00",
    onWarningContainer: "#DDEEBE",
    info: "#007DF3",
    onInfo: "#F2ECF3",
    infoContainer: "#0C3F74",
    onInfoContainer: "#D7E9FF",
    tint: "#6D65FE",
    tabIconDefault: "#A19CA2",
    tabIconSelected: "#6D65FE",
    icon: "#F2ECF3",
    shadow: "#000000",
    elevation1: "#1F1820",
    elevation2: "#302C31",
    elevation3: "#3F3355",
  },
};


// Old theme (kept commented out below for reference):
// export const Colors = {
//   light: {
//     // primary: "#A78BFB",
//     primary: "#98fb8bff",
//     onPrimary: "#FFFFFF",
//     primaryContainer: "#E9D9FC",
//     onPrimaryContainer: "#4B5666",
//     secondary: "#E9D9FC",
//     onSecondary: "#4B5666",
//     secondaryContainer: "#F5E5F7",
//     onSecondaryContainer: "#364050",
//     tertiary: "#7C38EE",
//     onTertiary: "#FFFFFF",
//     tertiaryContainer: "#F4EAFF",
//     onTertiaryContainer: "#364050",
//     background: "#F8F3FA",
//     onBackground: "#364050",
//     surface: "#FFFFFF",
//     onSurface: "#364050",
//     surfaceVariant: "#F4EAFF",
//     onSurfaceVariant: "#6C727E",
//     surfaceTint: "#A78BFB",
//     inverseSurface: "#2D2535",
//     inverseOnSurface: "#E1E7FD",
//     card: "#FFFFFF",
//     cardMuted: "#F4EAFF",
//     divider: "#E9D9FC",
//     scrim: "rgba(0,0,0,0.32)",
//     placeholder: "#6C727E",
//     outline: "#E9D9FC",
//     outlineVariant: "#E9D9FC",
//     border: "#E9D9FC",
//     input: "#E9D9FC",
//     ring: "#A78BFB",
//     text: "#364050",
//     textSecondary: "#6C727E",
//     textTertiary: "#8A9099",
//     error: "#e43c3cff",
//     onError: "#364050",
//     errorContainer: "#FDE3E3",
//     onErrorContainer: "#6C2E2E",
//     success: "#8C5DF8",
//     onSuccess: "#FFFFFF",
//     successContainer: "#EFE6FF",
//     onSuccessContainer: "#3D286B",
//     warning: "#6D29D8",
//     onWarning: "#FFFFFF",
//     warningContainer: "#ECDDFF",
//     onWarningContainer: "#37176A",
//     info: "#5A20B5",
//     onInfo: "#FFFFFF",
//     infoContainer: "#E8DDFA",
//     onInfoContainer: "#2F125E",
//     tint: "#A78BFB",
//     tabIconDefault: "#6C727E",
//     tabIconSelected: "#A78BFB",
//     icon: "#364050",
//     sidebar: "#E9D9FC",
//     sidebarForeground: "#364050",
//     sidebarPrimary: "#A78BFB",
//     sidebarPrimaryForeground: "#FFFFFF",
//     sidebarAccent: "#F5E5F7",
//     sidebarAccentForeground: "#364050",
//     sidebarBorder: "#E9D9FC",
//     sidebarRing: "#A78BFB",
//     chart1: "#A78BFB",
//     chart2: "#8C5DF8",
//     chart3: "#7C38EE",
//     chart4: "#6D29D8",
//     chart5: "#5A20B5",
//     shadow: "#000000",
//     elevation1: "#FFFFFF",
//     elevation2: "#F4EAFF",
//     elevation3: "#F5E5F7",
//   },
//   dark: {
//     // primary: "#C1AAFF",
//     primary: "#98fb8bff",
//     onPrimary: "#1E1916",
//     primaryContainer: "#4B3E5B",
//     onPrimaryContainer: "#D0D4DB",
//     secondary: "#3E3248",
//     onSecondary: "#D0D4DB",
//     secondaryContainer: "#4B3E5B",
//     onSecondaryContainer: "#E1E7FD",
//     tertiary: "#8C5DF8",
//     onTertiary: "#1E1916",
//     tertiaryContainer: "#3E3248",
//     onTertiaryContainer: "#D0D4DB",
//     background: "#1E1916",
//     onBackground: "#E1E7FD",
//     surface: "#2D2535",
//     onSurface: "#E1E7FD",
//     surfaceVariant: "#2D2535",
//     onSurfaceVariant: "#9BA2AE",
//     surfaceTint: "#C1AAFF",
//     inverseSurface: "#E1E7FD",
//     inverseOnSurface: "#1E1916",
//     card: "#2D2535",
//     cardMuted: "#2D2535",
//     divider: "#3E3248",
//     scrim: "rgba(0,0,0,0.55)",
//     placeholder: "#9BA2AE",
//     outline: "#3E3248",
//     outlineVariant: "#3E3248",
//     border: "#3E3248",
//     input: "#3E3248",
//     ring: "#C1AAFF",
//     text: "#E1E7FD",
//     textSecondary: "#9BA2AE",
//     textTertiary: "#7F8896",
//     error: "#FBA7A7",
//     onError: "#1E1916",
//     errorContainer: "#5A2F34",
//     onErrorContainer: "#FFDCDC",
//     success: "#A78BFB",
//     onSuccess: "#1E1916",
//     successContainer: "#3F3152",
//     onSuccessContainer: "#EDE4FF",
//     warning: "#7C38EE",
//     onWarning: "#E1E7FD",
//     warningContainer: "#3F2A68",
//     onWarningContainer: "#EBDFFF",
//     info: "#6D29D8",
//     onInfo: "#E1E7FD",
//     infoContainer: "#3B245E",
//     onInfoContainer: "#E6DBFF",
//     tint: "#C1AAFF",
//     tabIconDefault: "#9BA2AE",
//     tabIconSelected: "#C1AAFF",
//     icon: "#E1E7FD",
//     sidebar: "#3E3248",
//     sidebarForeground: "#E1E7FD",
//     sidebarPrimary: "#C1AAFF",
//     sidebarPrimaryForeground: "#1E1916",
//     sidebarAccent: "#4B3E5B",
//     sidebarAccentForeground: "#D0D4DB",
//     sidebarBorder: "#3E3248",
//     sidebarRing: "#C1AAFF",
//     chart1: "#C1AAFF",
//     chart2: "#A78BFB",
//     chart3: "#8C5DF8",
//     chart4: "#7C38EE",
//     chart5: "#6D29D8",
//     shadow: "#000000",
//     elevation1: "#2D2535",
//     elevation2: "#3E3248",
//     elevation3: "#4B3E5B",
//   },
// };

export const Fonts = Platform.select({
  ios: {
    sans: "Open Sans",
    serif: "Source Serif 4",
    rounded: "Open Sans",
    mono: "IBM Plex Mono",
  },
  default: {
    sans: "Open Sans",
    serif: "Source Serif 4",
    rounded: "Open Sans",
    mono: "IBM Plex Mono",
  },
  web: {
    sans: "'Open Sans', sans-serif",
    serif: "'Source Serif 4', serif",
    rounded: "'Open Sans', sans-serif",
    mono: "'IBM Plex Mono', monospace",
  },
});
