name: Publish production update

on:
  push:
    branches: ["main"]

jobs:
  publish_production_update:
    name: Publish production update
    type: update
    params:
      branch: ${{ github.ref_name || 'main' }}
